apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
  labels:
    app: express-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
      - name: express-app
        image: docker.io/itejas19/express-app:6.0
        ports:
        - containerPort: 3000
        env:
        - name: DB_SERVER
          valueFrom: 
            configMapKeyRef:
              name: app-config
              key: database_url
        - name: DB_NAME
          valueFrom: 
            configMapKeyRef:
              name: app-config
              key: database_name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-username
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-password              

---
apiVersion: v1
kind: Service
metadata:
  name: express-app-service
spec:
  selector:
    app: express-app
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000

