apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: docker.io/itejas19/express-app:4.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: DB_SERVER
          valueFrom: 
            configMapKeyRef:
              name: app-config
              key: database_url
        - name: DB_NAME
          valueFrom: 
            configMapKeyRef:
              name: app-config
              key: database_name

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000

